load("@io_bazel_rules_scala//scala:scala.bzl", "scala_binary", "scala_library")

scala_library(
    name = "greeting",
    srcs = ["Greeting.scala"],
    deps = [],
    visibility = ["//cmd/src/main/scala:__pkg__"],
)
