workspace(name = "ts_jest_cra")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "aspect_rules_js",
    sha256 = "6eaac9e07c6cac8d577fca0cd5362ca750ca5c60d20facac864ae358f39612a2",
    strip_prefix = "rules_js-1.6.7",
    url = "https://github.com/aspect-build/rules_js/archive/refs/tags/v1.6.7.tar.gz",
)

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")

rules_js_dependencies()

http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "5aae76dced38f784b58d9776e4ab12278bc156a9ed2b1d9fcd3e39921dc88fda",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/5.7.1/rules_nodejs-5.7.1.tar.gz"],
)

load("@rules_nodejs//nodejs:repositories.bzl", "DEFAULT_NODE_VERSION", "nodejs_register_toolchains")

nodejs_register_toolchains(
    name = "nodejs",
    node_version = DEFAULT_NODE_VERSION,
)

load("@aspect_rules_js//npm:npm_import.bzl", "npm_translate_lock")

npm_translate_lock(
    name = "npm",
    npm_package_lock = "//:package-lock.json",
    npmrc = "//:.npmrc",
    package_json = "//:package.json",
    verify_node_modules_ignored = "//:.bazelignore",
    public_hoist_packages = {
        "jest-watch-typeahead": [""],
        "eslint": [""],
    },
)

load("@npm//:repositories.bzl", "npm_repositories")

npm_repositories()
