load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# rules_scala
skylib_version = "1.0.3"
http_archive(
    name = "bazel_skylib",
    sha256 = "1c531376ac7e5a180e0237938a2536de0c54d93f5c278634818e0efc952dd56c",
    type = "tar.gz",
    url = "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/{}/bazel-skylib-{}.tar.gz".format(skylib_version, skylib_version),
)

rules_scala_version = "ceccd53b70974c644ac790fbda25f7cd325626a2"

http_archive(
    name = "io_bazel_rules_scala",
    sha256 = "b4cde3b7ea3b5b8d76a5f6957817a9893190eb6c9d22809dc09b7879caddf990",
    strip_prefix = "rules_scala-%s" % rules_scala_version,
    type = "zip",
    url = "https://github.com/bazelbuild/rules_scala/archive/%s.zip" % rules_scala_version,
)

load("@io_bazel_rules_scala//:scala_config.bzl", "scala_config")
scala_config()

load("@io_bazel_rules_scala//scala:scala.bzl", "rules_scala_setup", "rules_scala_toolchain_deps_repositories")

rules_scala_setup()

rules_scala_toolchain_deps_repositories(fetch_sources = True)

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
rules_proto_dependencies()
rules_proto_toolchains()

load("@io_bazel_rules_scala//scala:toolchains.bzl", "scala_register_toolchains")
scala_register_toolchains()

# optional: setup ScalaTest toolchain and dependencies
load("@io_bazel_rules_scala//testing:scalatest.bzl", "scalatest_repositories", "scalatest_toolchain")
scalatest_repositories()
scalatest_toolchain()

load("@io_bazel_rules_scala//scala/scalafmt:scalafmt_repositories.bzl", "scalafmt_default_config", "scalafmt_repositories")
scalafmt_default_config()
scalafmt_repositories()

# rules_jvm_external

# RULES_JVM_EXTERNAL_TAG = "4.5"
# RULES_JVM_EXTERNAL_SHA ="b17d7388feb9bfa7f2fa09031b32707df529f26c91ab9e5d909eb1676badd9a6"
# 
# http_archive(
#     name = "rules_jvm_external",
#     strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
#     sha256 = RULES_JVM_EXTERNAL_SHA,
#     url = "https://github.com/bazelbuild/rules_jvm_external/archive/refs/tags/%s.zip" % RULES_JVM_EXTERNAL_TAG,)
# 
# load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")
# 
# rules_jvm_external_deps()
# 
# load("@rules_jvm_external//:setup.bzl", "rules_jvm_external_setup")
# 
# rules_jvm_external_setup()
# 
# load("@rules_jvm_external//:defs.bzl", "maven_install")
# maven_install(
#     artifacts = [
#         "com.typesafe:config:1.4.2"
#     ],
#     fetch_sources = True,
#     repositories = [
#         "https://repo1.maven.org/maven2",
#     ],
# )
