load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library")

scala_library(
    name = "base",
    srcs = ["base.scala"],
    resources = glob(["resources/**"]),
    visibility = ["//visibility:public"],
)

